services:
  - name: techsellence-aura
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi"
    postdeploy:
      - python manage.py makemigrations
      - python manage.py migrate