# Generated by Django 5.1 on 2024-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bse_code', models.CharField(blank=True, max_length=10, null=True)),
                ('nse_code', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to_earning', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('market_capitalization', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_profit_latest_quarter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yoy_quarterly_profit_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_cash_generated_from_ebidta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to_book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ev_by_fcf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('merged_data', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_by', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
